import { useState, useEffect } from 'react';
import type { Product } from '@/types/product';

// In production this JSON is generated by the Feishu sync script via GitHub Actions.
// During local dev, place a products.json in public/data/ or src/data/.
const DATA_URL = '/data/products.json';

export function useProducts() {
  const [products, setProducts] = useState<Product[]>([]);
  const [isLoaded, setIsLoaded] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(DATA_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load products (${res.status})`);
        return res.json();
      })
      .then((data: Product[]) => {
        setProducts(data);
        setIsLoaded(true);
      })
      .catch((err) => {
        console.warn('Could not load products.json, using empty list.', err);
        setProducts([]);
        setIsLoaded(true);
        setError(err.message);
      });
  }, []);

  return { products, isLoaded, error };
}
